<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <PropertyGroup Label="Scarlet.Tailwind">
    <TailwindRuntimeDownload>true</TailwindRuntimeDownload>
    <TailwindVersionDownload>4.3.3</TailwindVersionDownload>
    <TailwindRuntimeDirectory>$(MSBuildProjectDirectory)/../../tools</TailwindRuntimeDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <EmbeddedResource Remove="tests\**\*" />
    <None Remove="tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.6" PrivateAssets="all" />
    <PackageReference Include="Scarlet.Tailwind.MSBuild" Version="1.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <TailwindBeforeStaticWebAssets Include="Styles/app.css">
      <OutputPath>wwwroot/css/app.css</OutputPath>
      <Map Condition="'$(Configuration)' == 'Debug'">%(OutputPath).map</Map>
    </TailwindBeforeStaticWebAssets>

    <Watch Include="Styles\**\*.css;**\*.razor;**\*.razor.cs;**\*.cshtml;**\*.html;wwwroot\**\*.js" />
  </ItemGroup>

</Project>
